### ISSUE TITLE
Hey,

### ISSUE THREAD

**Issue by brynnie1** [propstg/ambulance-mission#13]
Hey,

You would need to change `Config.ActivationKeyText` from `"INPUT_CONTEXT"` to whatever the appropriate "Name" is for value you used for `Config.ActivationKey`. You should be able to find the name on the [controls page](https://docs.fivem.net/game-references/controls/) in the FiveM docs.

Let me know if you have any issues. Thanks!

_Originally posted by @propstg in https://github.com/propstg/ambulance-mission/issues/12#issuecomment-506139344_

So still having hte issue so I look in the link you sent me - and the keybind is 213	INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY	HOME	RB >

I change it here 
Config.ActivationKey = 213
Config.ActivationKeyText = 'Home'

But still comes up with Press E, I'm doing something wrong but don't know what

**Comment by propstg** [comment]
Hey, the second column is the one you want, so it should be "INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY".

I just tried this out and it worked for me, showing `HOME` in the help message:
```
Config.ActivationKey = 213
Config.ActivationKeyText = 'INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY'
```

However, 213 is RB on the controller, which means if you hit the handbrake, you will end the mission. The following might be friendlier for controller users, as it will make the start/quit key the back button on the controller, instead of a button that is used for driving, and it will still allow you to use "Home" on the keyboard:
```
Config.ActivationKey = 212
Config.ActivationKeyText = 'INPUT_FRONTEND_SOCIAL_CLUB'
```

**Comment by brynnie1** [comment]
Thank you so much it fricking worked, thanks for your assistance

**Comment by propstg** [comment]
Great! Glad it's working.
