### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MolenBeekRP** [propstg/ambulance-mission#23]
**Describe the bug**
I have the edited don for Onesync with the dead message problem (mission failt after level 1)
It works I can now drive to more pets (npc) but now the not showing up annymore.... I drive to a ped (npc) and I only see a waitpoint and no npc. If I stop I get the message that I need to go to the hospital to bring hem in or go to the second ped (npc). But no peds (npc) showing annymore... Is here also a sollution for? so peds (npc) we can see them again

**To Reproduce**
Detailed steps to reproduce the behavior.
tryed to reset te script couple of times

**Likely essential information**
1. Are there any errors in the server console?
No error or info in console

2. Are you using OneSync?
YES

3. What server version are you using?
31.94
4. If the player's game is crashing, is there an error message displayed to the player when the game crashes?
NOPE

5. Does the issue only happen occasionally? or every time?
Every time

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be screenshots of errors in console.
No screenshots because there is nothing to show then no peds (npc) are there 

**Additional context**

**Comment by propstg** [comment]
Hi @MolenBeekRP,

Thanks for the details. I think I have a better idea of what might be happening, now. Looking at the description for OneSync Infinity (now the default for OneSync?) at https://forum.cfx.re/t/onesync-infinity-how-to-use-it/996612, it looks like the cause is probably the game either culling or not creating the peds in the first place.

> * Player ped/vehicle culling. No entities will be created on clients outside a ‘focus zone’, which currently is hardcoded to 300 units around a player. We’re still looking for a better algorithm.
> * Player culling. No players will be created/deleted locally outside of the focus zone too. This means that all player iteration will have to happen server-side.

I think this makes sense... If the script thinks the ped is dead instantly because it can't find them because they were either instantly culled or never spawned, then the fix in the other PR would get past that check by disabling checking if the ped is alive altogether (which is what it's effectively doing).

I haven't been able to recreate any of the OneSync-related errors with my bus script (which also spawns peds), but I'll try adding an option (hopefully tomorrow evening) to delay spawning peds until the player is at/near the location, to see if that fixes the problem in OneSync.

**Comment by propstg** [comment]
Hi @MolenBeekRP, please check out the `delay-spawning-peds` branch and give it a try, when you have a chance.

I wasn't able to recreate the error on my end, so I'm not sure if this will fix the issue you're seeing. But, if the issue is related to the ped not being created because of distance, then I think this might work.

**Comment by EGUltraTM** [comment]
Checked the sript out today and had the same issue on onesync that it directly showed patient died. 
With youre delay-spawing-peds branch it works 👍

**Comment by propstg** [comment]
Awesome, thanks @EGUltraTM! I'll go ahead and merge this.

@MolenBeekRP, please reopen this ticket if you have any issues with the fix.
