### ISSUE TITLE
Strange issue (I'm dumb)

### ISSUE THREAD

**Issue by daddyafx** [propstg/ambulance-mission#27]
**Describe the bug**
Regardless of what I change the config.Formulas to for payout, additional money is awarded upon level-up.

Even if I manually change the wrapper to `**ESX.GetPlayerFromId(source).addMoney(50)**`, it will be $50 per patient delivered, but upon finishing level 1, you total $101, level 2, 502 or 602, level 3 1603 etc etc

**Likely essential information**
1. Are there any errors in the server console?
No
2. Are you using OneSync?
Yes
3. What server version are you using?
Newest

I realize this is intended functionality, it's just economy breaking for my server and the lowest payout I'm able to achieve is something along the lines of $1000 per 5-10 minutes. So basically the script is A+, I just really need it to not automatically award you on level completion, and only award you on passenger drop-off. (Even if it does award you on completion, but only per passenger, this would be ideal).

Full disclosure I use this for both my EMS, and have converted locales/vehicles/job to use it as for taxi drivers as well, as frankly it's 150% better than any _actual_ taxi job I've been able to find.

**Comment by propstg** [comment]
Hey @daddyafx,

Sorry, I won't be able to look into this deeply for a couple of weeks, and it's been long enough since I touched this project that I don't think I can give a quick, definite answer or mess around with making any quick code changes myself. I'd probably start by trying the below, maybe.

Does it still misbehave if you change the formula to just return a fixed number? Like `function(level) return 50 end`? That should make the notification and the amount at least be the same, in case that's the discrepancy.

I would _expect_ this formula to work, if you want $50/person at the end of a level, but I'm not sure what would cause what you're seeing if you already tried something like this, since the level should be equal to the number of peds (iirc).
```
    moneyPerLevel               = function(level)                   return 50 * level end,
```

If you want the player paid out as they drop off, you could try bumping lines 313 and 314 of client/main.lua up out of that if block and pass in `numberDroppedOff` instead of `level` (with the above change to the moneyPerLevel formula).
```
        Wrapper.TriggerServerEvent(SERVER_EVENT, numberDroppedOff)
        Scaleform.ShowAddMoney(Wrapper._('add_money', Config.Formulas.moneyPerLevel(numberDroppedOff)))
```

Alternatively, I guess I never got around to merging it, but the rp-mode branch (diff and brief explanation here: https://github.com/propstg/ambulance-mission/pull/26) has a "continuous mode" that would let you lock it to level 1, which should at least stop the amount at the end of the level from growing (at the expense of the game not automatically ending, only one ped spawned at a time, and maybe causing issues with any modifications you've made).

> Full disclosure I use this for both my EMS, and have converted locales/vehicles/job to use it as for taxi drivers as well, as frankly it's 150% better than any actual taxi job I've been able to find.

That's very cool to hear! Good job repurposing it. I'd love to take a look at it/accept a PR when I get back, if you're interested in adding it to this script.

**Comment by propstg** [comment]
Please reopen if the above didn't help resolve your issue.
